# Generated by Django 2.0.7 on 2018-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='how_was_the_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
