# Generated by Django 2.0.7 on 2018-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_journal_how_was_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='daily_streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
