# Generated by Django 2.0.7 on 2018-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habit_daily_streak_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='habit',
            name='week_day',
        ),
        migrations.AddField(
            model_name='habit',
            name='week_day',
            field=models.ManyToManyField(blank=True, null=True, to='habit.Week'),
        ),
    ]
