# Generated by Django 2.0.7 on 2018-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_auto_20180731_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(blank=True, help_text='Example: Hit the gym at 5 pm.', null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[(1, 'hourly'), (2, 'daily'), (3, 'weekly')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='hourly_interval',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Example: Drink a glass of water every 2 hours.', null=True, verbose_name='interval in hours'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='week_day',
            field=models.ManyToManyField(blank=True, help_text='Example: Clean the room every Sunday.', null=True, to='habit.Week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_day',
            field=models.CharField(blank=True, choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thursday'), ('5', 'friday'), ('6', 'saturday'), ('7', 'sunday')], max_length=1, null=True),
        ),
    ]
