# Generated by Django 2.0.7 on 2018-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_auto_20180731_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='week_day',
            field=models.ManyToManyField(help_text='Example: Clean the room every Sunday.', to='habit.Week'),
        ),
    ]
