# Generated by Django 2.0.7 on 2018-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_auto_20180731_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('1', 'hourly'), ('2', 'daily'), ('3', 'weekly')], default=1, max_length=1),
        ),
    ]
