# Generated by Django 2.0.7 on 2018-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_auto_20180801_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
