# Generated by Django 2.0.7 on 2018-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0010_auto_20180801_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='week_day',
            field=models.ManyToManyField(blank=True, help_text='Example: Clean the room every Sunday.', null=True, to='habit.Week'),
        ),
    ]
